### ISSUE TITLE
ok so I guess I am just not understanding this -_-

### ISSUE THREAD

**Issue by warlord1352** [AdamGagorik/pydarkstar#11]
So I'm guessing my paths are all messed up and after writing on the forums Teo mentioned it is most likely my paths that are not working and to post here. As I stated in the forums any time I try to open any of the files batch/or otherwise they just instantly close. 2nd problem is when I try to use the batch file I am not understanding the whole "python3" part. Which file is it supposed to be using and from where? I either have my directory wrong or I'm using the wrong file. I've tried the python3 in Anaconda which kind of seemed to work but then I had a ton of errors in all the modules inside that. Or I tired using the python3 inside python3.4 folder and that didn't seem to work. I would really like to use this as it seems to awesome and helpful but I am just completely at a loss -_-;. Any help or advice would be much appreciated! Thank for all the awesome hard work and and thanks for any help! =)

**Comment by warlord1352** [comment]
![broker_fail](https://user-images.githubusercontent.com/15023912/36875003-f802bd24-1d62-11e8-9934-dac9acf4e1b9.JPG)

So I think this is wrong but again I'm not sure where to go.....

**Comment by AdamGagorik** [comment]
I have updated the setup instructions to use a Conda environment.  The use of a Conda environment should simply the paths on your system.  Please retry with the new instructions.
