### ISSUE TITLE
Python3.6

### ISSUE THREAD

**Issue by Joncuan** [AdamGagorik/pydarkstar#16]
File "./broker.py", line 12, in <module>
    import pydarkstar
  File "/root/pydarkstar/pydarkstar/__init__.py", line 42, in <module>
    from . import common
  File "/root/pydarkstar/pydarkstar/common.py", line 8
    def create_path(*args, absolute=True, dt_fmt='%Y_%m_%d_%H_%M_%S', dt=None,
                                  ^
SyntaxError: invalid syntax

**Comment by AdamGagorik** [comment]
I think this appears when you try to execute things with Python2 instead of Python3.  You can always check what you are running by executing python --version in the terminal.  A similar issue was observed in #12.
