### ISSUE TITLE
Conda doesn't resolve dependencies on environment creation

### ISSUE THREAD

**Issue by AZDserver** [AdamGagorik/pydarkstar#17]
I've installed Python 3.7.3 and Anaconda from: https://www.anaconda.com/distribution/

When I try to create the conda environment "conda env create -f environment.yml" , it fails at Solving Environment: failed

ResolvePackageNotFound:

ruamel_yaml==0.15.46=py37h1de35cc_0
numpy-base==1.16.4=py37h6575580_0
sqlalchemy==1.3.4=py37h1de35cc_0
mistune==0.8.4=py37h1de35cc_0
icu==58.2=h4b95b61_1
libcxx==4.0.1=hcfea43d_1
libsodium==1.0.16=h3efe00b_0
libedit==3.1.20181209=hb402a30_0
matplotlib==3.1.0=py37h54f8f79_0
pyrsistent==0.14.11=py37h1de35cc_0
jupyterlab==0.35.5=py37hf63ae98_0
mkl==2019.4=233
libpng==1.6.37=ha441bb4_0
mkl-service==2.0.2=py37h1de35cc_0
freetype==2.9.1=hb4e5f40_0
pcre==8.43=h0a44026_0
libffi==3.2.1=h475c297_4
xz==5.2.4=h1de35cc_4
pillow==6.0.0=py37hb68e598_0
yaml==0.1.7=hc338f04_2
libcxxabi==4.0.1=hcfea43d_1
llvm-openmp==4.0.1=hcfea43d_1
zeromq==4.3.1=h0a44026_3
mkl_fft==1.0.12=py37h5e564d8_0
gettext==0.19.8.1=h15daf44_3
ptyprocess==0.6.0=py37_0
cryptography==2.6.1=py37ha12b0ac_0
numpy==1.16.4=py37hacdab7b_0
sqlite==3.27.2=ha441bb4_0
libtiff==4.0.10=hcb84e12_2
ncurses==6.1=h0a44026_1
expat==2.2.6=h0a44026_0
statsmodels==0.9.0=py37h1d22016_0
tk==8.6.8=ha441bb4_0
qt==5.9.7=h468cd18_1
dbus==1.13.6=h90a0687_0
pyzmq==18.0.0=py37h0a44026_0
zstd==1.3.7=h5bba6e5_0
pandas==0.24.2=py37h0a44026_0
python==3.7.3=h359304d_0
scipy==1.2.1=py37h1410ff5_0
intel-openmp==2019.4=233
mkl_random==1.0.2=py37h27c97d8_0
pyyaml==5.1=py37h1de35cc_0
libgfortran==3.0.1=h93005f0_2
markupsafe==1.1.1=py37h1de35cc_0
kiwisolver==1.1.0=py37h0a44026_0
python.app==2=py37_9
pyqt==5.9.2=py37h655552a_2
glib==2.56.2=hd9629dc_0
tornado==6.0.2=py37h1de35cc_0
pycosat==0.6.3=py37h1de35cc_0
sip==4.19.8=py37h0a44026_0
jpeg==9b=he5867d9_2
readline==7.0=h1de35cc_5
scikit-learn==0.21.2=py37h27c97d8_0
libiconv==1.15=hdd342a3_7
cffi==1.12.2=py37hb5b8e2f_1
appnope==0.1.0=py37_0
openssl==1.1.1c=h1de35cc_1
zlib==1.2.11=h1de35cc_3

Anaconda is supposed to install all these dependencies on it's own, no?

**Comment by AdamGagorik** [comment]
It is.  You are right.  It should work.  What OS are you on?

I will try to make a striped down environment with the minimal packages.  This was just a clone of my environment on OSX and might have some package that isn't available on your system.

**Comment by AdamGagorik** [comment]
I have updated and simplified the Conda environment yaml file.
It should be the bare minimum required packages.

```yaml
name: pydarkstar
channels:
  - anaconda
  - defaults
dependencies:
  - asn1crypto=0.24.0=py37_0
  - beautifulsoup4=4.7.1=py37_1
  - ca-certificates=2019.5.15=0
  - certifi=2019.3.9=py37_0
  - cffi=1.12.3=py37hb5b8e2f_0
  - cryptography=2.7=py37ha12b0ac_0
  - idna=2.8=py37_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - ncurses=6.1=h0a44026_1
  - openssl=1.1.1=h1de35cc_0
  - pip=19.1.1=py37_0
  - pyaml=19.4.1=py_0
  - pycparser=2.19=py37_0
  - pymysql=0.9.3=py37_0
  - python=3.7.3=h359304d_0
  - pyyaml=5.1=py37h1de35cc_0
  - readline=7.0=h1de35cc_5
  - setuptools=41.0.1=py37_0
  - six=1.12.0=py37_0
  - soupsieve=1.8=py37_0
  - sqlalchemy=1.3.4=py37h1de35cc_0
  - sqlite=3.28.0=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - wheel=0.33.4=py37_0
  - xz=5.2.4=h1de35cc_4
  - yaml=0.1.7=hc338f04_2
  - zlib=1.2.11=h1de35cc_3
```

If this still does not work on your system, can you please try the following?

```
conda create -n pydarkstar python=3.7
activate pydarkstar
conda install pyaml
conda install pymysql
conda install sqlalchemy
conda install -c anaconda beautifulsoup4
```

If that works, can you please provide me the environment.yml file?
Run the following command and attach it here.

```bash
conda env export > environment.yml
```

**Comment by AZDserver** [comment]
Ya, I think it was the OS issue. I'm on Windows 10. I got it to work by stripping the second =[hash] after each package, and then for the ones it couldn't resolve, I just removed them from the dependencies list, so I know there are extraneous dependencies in there. It'd be best if you updated this file with the minimal packages without the OSX appended version keys.

**Comment by AdamGagorik** [comment]
Thanks.  Sorry for the confusion.

**Comment by AZDserver** [comment]
Here's my version that worked for me, I'm pretty sure there are extra packages in this list:

name: pydarkstar
channels:
  - anaconda
  - defaults
dependencies:
  - alabaster=0.7.12
  - asn1crypto=0.24.0
  - atomicwrites=1.3.0
  - attrs=19.1.0
  - babel=2.7.0
  - backcall=0.1.0
  - beautifulsoup4=4.7.1
  - blas=1.0
  - bleach=3.1.0
  - bokeh=1.2.0
  - ca-certificates=2019.5.15
  - certifi=2019.3.9
  - cffi=1.12.2
  - chardet=3.0.4
  - conda=4.6.14
  - cryptography=2.6.1
  - cycler=0.10.0
  - decorator=4.4.0
  - defusedxml=0.6.0
  - docutils=0.14
  - entrypoints=0.3
  - expat
  - freetype=2.9.1
  - icu=58.2
  - idna=2.8
  - imagesize=1.1.0
  - importlib_metadata=0.17
  - intel-openmp=2019.4
  - ipykernel=5.1.1
  - ipython=7.5.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.2
  - jedi=0.13.3
  - jinja2=2.10.1
  - joblib=0.13.2
  - jpeg=9b
  - jsonschema=3.0.1
  - jupyter=1.0.0
  - jupyter_client=5.2.4
  - jupyter_console=6.0.0
  - jupyter_core=4.4.0
  - jupyterlab
  - jupyterlab_server=0.2.0
  - kiwisolver=1.1.0
  - libiconv=1.15
  - libpng=1.6.37
  - libsodium=1.0.16
  - libtiff=4.0.10
  - markupsafe=1.1.1
  - matplotlib=3.1.0
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.0.2
  - mkl_fft=1.0.12
  - mkl_random=1.0.2
  - more-itertools=7.0.0
  - nbconvert=5.5.0
  - nbformat=4.4.0
  - notebook=5.7.8
  - numpy=1.16.4
  - numpy-base=1.16.4
  - olefile=0.46
  - openssl=1.1.1c
  - packaging=19.0
  - pandas=0.24.2
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.4.0
  - patsy=0.5.1
  - pcre=8.43
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=6.0.0
  - pip=19.0.3
  - pluggy=0.12.0
  - prometheus_client=0.6.0
  - prompt_toolkit=2.0.9
  - py=1.8.0
  - pycosat=0.6.3
  - pycparser=2.19
  - pygments=2.4.2
  - pymysql=0.9.3
  - pyopenssl=19.0.0
  - pyparsing=2.4.0
  - pyqt=5.9.2
  - pyrsistent=0.14.11
  - pysocks=1.6.8
  - pytest=4.6.2
  - python=3.7.3
  - python-dateutil=2.8.0
  - pytz=2019.1
  - pyyaml=5.1
  - pyzmq=18.0.0
  - qt=5.9.7
  - qtconsole=4.5.1
  - requests=2.22.0
  - ruamel_yaml=0.15.46
  - scikit-learn=0.21.2
  - scipy=1.2.1
  - seaborn=0.9.0
  - send2trash=1.5.0
  - setuptools=41.0.0
  - sip=4.19.8
  - six=1.12.0
  - snowballstemmer=1.2.1
  - soupsieve=1.8
  - sphinx=2.1.0
  - sphinx_rtd_theme=0.4.3
  - sphinxcontrib-applehelp=1.0.1
  - sphinxcontrib-devhelp=1.0.1
  - sphinxcontrib-htmlhelp=1.0.2
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.2
  - sphinxcontrib-serializinghtml=1.1.3
  - sqlalchemy=1.3.4
  - sqlite=3.27.2
  - statsmodels=0.9.0
  - terminado=0.8.2
  - testpath=0.4.2
  - tk=8.6.8
  - tornado=6.0.2
  - traitlets=4.3.2
  - urllib3=1.24.1
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.1
  - widgetsnbextension=3.4.2
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.3.1
  - zipp=0.5.1
  - zlib=1.2.11
  - zstd=1.3.7
