### ISSUE TITLE
Could not find conda environment: pydarkstar

### ISSUE THREAD

**Issue by maxper87** [AdamGagorik/pydarkstar#18]
When i write this:
conda activate pydarkstar
it says  Could not find conda environment: pydarkstar
You can list all discoverable environments with conda info --envs.

**Comment by maxper87** [comment]
(base) C:\WINDOWS\system32>cd /D C:\Users\Max\Desktop\pydarkstar-master\bin

(base) C:\Users\Max\Desktop\pydarkstar-master\bin>conda env remove --name pydarkstar

(base) C:\Users\Max\Desktop\pydarkstar-master\bin>conda env create -f environment.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - zlib==1.2.11=h1de35cc_3
  - cffi==1.12.3=py37hb5b8e2f_0
  - sqlalchemy==1.3.4=py37h1de35cc_0
  - tk==8.6.8=ha441bb4_0
  - libcxx==4.0.1=hcfea43d_1
  - yaml==0.1.7=hc338f04_2
  - cryptography==2.7=py37ha12b0ac_0
  - openssl==1.1.1=h1de35cc_0
  - python==3.7.3=h359304d_0
  - sqlite==3.28.0=ha441bb4_0
  - libcxxabi==4.0.1=hcfea43d_1
  - pyyaml==5.1=py37h1de35cc_0
  - libffi==3.2.1=h475c297_4
  - libedit==3.1.20181209=hb402a30_0
  - xz==5.2.4=h1de35cc_4
  - ncurses==6.1=h0a44026_1
  - readline==7.0=h1de35cc_5


(base) C:\Users\Max\Desktop\pydarkstar-master\bin>conda activate pydarkstar
Could not find conda environment: pydarkstar
You can list all discoverable environments with `conda info --envs`.


(base) C:\Users\Max\Desktop\pydarkstar-master\bin>

**Comment by wadski** [comment]
I am having this same issue as well.

**Comment by AdamGagorik** [comment]
Looks like the environment fails to create on your system.  Sorry about that.  I will try to fix the `environment.yml` to handle your system.

In the mean time you can try using conda or pip for install the dependencies one by one.

```bash
conda create -n pydarkstar python=3.7
conda activate pydarkstar
conda install sqlalchemy
conda install pymysql
conda install -c anaconda beautifulsoup4
conda install pyyaml
```

I might have some of those commands wrong.  Google ‘conda install ...’ if I do.

If you get this working you can export the environment file for me to compare to with ‘conda env export —explicit > environment.yml’.

**Comment by wadski** [comment]
Hi Adam, Thanks for the reply. I am trying it out now and will report back with what i find out.

**Comment by vrtra** [comment]
No luck still saying C:\pydarkstar\environment.yml' file not found when trying to activate the environment. it wont point to \pydarkstar\bin\environment.yml'

**Comment by wadski** [comment]
` C:\vrtra\tools\PyDarkstar\bin>conda activate pydarkstar

(pydarkstar) C:\vrtra\tools\PyDarkstar\bin>.\broker.py
[2019-08-19 22:16:30][ 7052][ERROR]: ModuleNotFoundError
Traceback (most recent call last):
  File "C:\vrtra\tools\PyDarkstar\bin\broker.py", line 8, in <module>
    import pydarkstar
ModuleNotFoundError: No module named 'pydarkstar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\vrtra\tools\PyDarkstar\pydarkstar\__init__.py", line 19, in <module>
    import pymysql
ModuleNotFoundError: No module named 'pymysql'
[2019-08-19 22:16:30][ 7052][ERROR]: pip install pymysql

(pydarkstar) C:\vrtra\tools\PyDarkstar\bin>

still no luck`

**Comment by AdamGagorik** [comment]
Well I simplified the environment file down to this bare minimum.

```yaml
name: pydarkstar
channels:
  - anaconda
  - defaults
dependencies:
  - beautifulsoup4=4.7.1
  - pyaml=19.4.1
  - pymysql=0.9.3
  - python=3.7.3
  - pyyaml=5.1
  - sqlalchemy=1.3.4
```

It is possible that if you retry `conda env create -f environment.yml` it will not error out this time.

**Comment by AdamGagorik** [comment]
> ` C:\vrtra\tools\PyDarkstar\bin>conda activate pydarkstar
> 
> (pydarkstar) C:\vrtra\tools\PyDarkstar\bin>.\broker.py
> [2019-08-19 22:16:30][ 7052][ERROR]: ModuleNotFoundError
> Traceback (most recent call last):
> File "C:\vrtra\tools\PyDarkstar\bin\broker.py", line 8, in 
> import pydarkstar
> ModuleNotFoundError: No module named 'pydarkstar'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "C:\vrtra\tools\PyDarkstar\pydarkstar__init__.py", line 19, in 
> import pymysql
> ModuleNotFoundError: No module named 'pymysql'
> [2019-08-19 22:16:30][ 7052][ERROR]: pip install pymysql
> 
> (pydarkstar) C:\vrtra\tools\PyDarkstar\bin>
> 
> still no luck i had installed pymysql previously also

These errors suggest to me that:

  1) you created an environment
  2) this environment does not have pymysql installed
  3) you possibly installed pymysql into a different environment

Trying the following will disprove this hypothesis.

```base
conda activate pydarkstar
python
import pymysql
```

To install a module you must:

  1.  Make sure the correct environment is active: `conda activate pydarkstar`
  2.  Use `conda install module-name` or `pip install module-name`
  3.  Test that you can import the module with `python -c "import module-name"`

**Comment by wadski** [comment]
Hi Adam,

I deleted pydarkstar and stared from scratch. 

I got no issues with the environment this time but, after following initial setup from your website i came across the same errors. 
(i followed step by step)
`
(base) C:\Users\vrtra>conda activate pydarkstar

(pydarkstar) C:\Users\vrtra>cd C:\pydarkstar\bin

(pydarkstar) C:\pydarkstar\bin>.\broker.py
[2019-08-24 16:52:42][11204][ERROR]: ModuleNotFoundError
Traceback (most recent call last):
  File "C:\pydarkstar\bin\broker.py", line 8, in <module>
    import pydarkstar
ModuleNotFoundError: No module named 'pydarkstar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\pydarkstar\pydarkstar\__init__.py", line 19, in <module>
    import pymysql
ModuleNotFoundError: No module named 'pymysql'
[2019-08-24 16:52:42][11204][ERROR]: pip install pymysql
`

So going back over your steps of installing the dependencies one by one it i get this on all of them. showing that the dependencies did install.
`
(pydarkstar) C:\pydarkstar\bin>conda install pymysql
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.


(pydarkstar) C:\pydarkstar\bin>`

Here its showing my environments are ok.
`# conda environments:
#
base                     C:\Users\vrtra\Anaconda3
environment.yml          C:\Users\vrtra\Anaconda3\envs\environment.yml
pydarkstar            *  C:\Users\vrtra\Anaconda3\envs\pydarkstar

`
So i ran this:
`(base) C:\Users\vrtra>conda activate pydarkstar

(pydarkstar) C:\Users\vrtra>python
Python 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymysql
>>>
`
It just returns blank, nothing. 

So the part im unclear on is this:

`
To install a module you must:

Make sure the correct environment is active: conda activate pydarkstar
Use conda install module-name or pip install module-name
Test that you can import the module with python -c "import module-name"
`
What is the name of the module? Ive tried broker, refill etc. no luck. 

This is a clean install following step by step from your website. So im not sure what could be wrong.

**Comment by wadski** [comment]
I solved the issue, but the bat files will not run them so i have to open prompt to run each time. better than nothing :P thx

**Comment by wadski** [comment]
if i run refill bat it gives this error.

Traceback (most recent call last):
  File "C:\pydarkstar\pydarkstar\logutils.py", line 45, in capture
    yield
  File "refill.py", line 21, in <module>
    pydarkstar.apps.refill.run.main()
  File "C:\pydarkstar\pydarkstar\apps\refill\run.py", line 35, in main
    raise RuntimeError('refilling all items from auction house is dangerous. use --force')
RuntimeError: refilling all items from auction house is dangerous. use --force
[2019-08-24 18:35:15][ 5848][INFO ]: exit

**Comment by AdamGagorik** [comment]
That is not really an error, it is asking you to use the `--force`.  This is so that you do not accidentally erase the AH data if you do not want to.
