### ISSUE TITLE
scrape might have hung

### ISSUE THREAD

**Issue by TeoTwawki** [AdamGagorik/pydarkstar#2]
Just when we thought we were home free! Dun dun dunnnnn!
```
[2015-01-14 19:49:52][ 3460][INFO ]: (0x2cfaa70) FFXIAHScrubber: category 60/60
: http://www.ffxiah.com/browse/62/grips
[2015-01-14 19:49:53][ 3460][INFO ]: (0x2cfaa70) FFXIAHScrubber: getting data
[2015-01-14 19:49:53][ 3460][INFO ]: (0x2cfaa70) FFXIAHScrubber: threads = -1
```
It just sort of stopped right there, its been sitting there using around 1% cpu for the last 40 min.
I know the initial scrape takes some time, but I don't recall the prior version ever appearing to have stopped. Going to leave it sit for another hour and if this finishes, I'll close the issue here.

**Comment by AdamGagorik** [comment]
Use --verbose, I think its just downloading stuff.  It is a little more robust with checking things but that slows it down some.  The --verbose mode shows you a percentage finished.

Btw, if you just want to see it work for a few items:

```bash
python ./scurb.py --verbose --itemids 1 2 3 4 5
```

Also, I put a finished items.csv in the data folder, if you just want that - its from a couple days ago.

**Comment by TeoTwawki** [comment]
Ah ok, thanks.
