### ISSUE TITLE
AH Population

### ISSUE THREAD

**Issue by rostam420** [AdamGagorik/pydarkstar#25]
Hi guys im sure this is a common issue but I cannot seem to find the answer trolling the net

I am able to run pydarkstar with the provided information but I am unable to get the AH to populate items 
when a character puts something up in the auction house py does purchase it 
I have not customized or edited the items.csv from what I can tell by looking at the file it should dump quite a few items into the AH by default unless im missing something obvious

**Comment by rostam420** [comment]
![image](https://user-images.githubusercontent.com/65086105/81481198-24400300-91e3-11ea-8dfa-b499090e5560.png)

**Comment by rostam420** [comment]
![image](https://user-images.githubusercontent.com/65086105/81481232-59e4ec00-91e3-11ea-873b-eb484587bf59.png)

**Comment by AdamGagorik** [comment]
I think it is somewhat of a flaw in the system that the broker will not initially restock the items until after that `config.restock` time has elapsed (by default that is 3600 seconds or 1 hour).

```python
    while True:
        now = datetime.datetime.now()
        delta = (now - last).total_seconds()
        elapsed = (now - start).total_seconds()
        logging.debug('time=%012.1f s last restock=%012.1f s next restock=%012.1f s',
                      elapsed, delta, opts.restock - delta)

        if delta >= opts.restock:
            logging.debug('restocking...')
            manager.restock_items(itemdata=idata)
            last = datetime.datetime.now()
```

I think what you have to do is 1) lower the restock time - a bad idea probably or 2) run the `refill` app once to set the initial stock of items.

**Comment by AdamGagorik** [comment]
As this is more of question and I think the answer is to run the `refill` app or set the `config.restock` parameter I will close this for now.
