### ISSUE TITLE
pydarkstar AH will not work

### ISSUE THREAD

**Issue by PHSapper** [AdamGagorik/pydarkstar#32]
I have tried to install this several times and can not seem to get it to do anything at all remotely close to installing or setting up. Any help or updated files would be helpful thank you in advance.

**Comment by AdamGagorik** [comment]
I can't really help without more information.  Is there an error you can paste here?

**Comment by PHSapper** [comment]
> 

There is no error coming up? When I try to install following the tutorial when I double click the :Double click on \pydarkstar\makebin.py to create base files: nothing happens along with when i click the scub.py a window pops up then immediately disappears?

**Comment by AdamGagorik** [comment]
That is common windows thing.  These are command line applications and not really for double clicking.  Instead of double clicking, you need to be opening a terminal and running it.

For example, [here](http://adamgagorik.github.io/pydarkstar/generated/usage.html#example):

![image](https://user-images.githubusercontent.com/5294486/163909123-e4ff811b-d2f4-4cb1-804f-b8767d4eb06d.png)

**Comment by AdamGagorik** [comment]
To open the terminal, find it in the start menu.

![image](https://user-images.githubusercontent.com/5294486/163909269-f2c63595-5fae-48a1-826f-91b1fd615c1d.png)

**Comment by PHSapper** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/103973173/163911046-9e3271cd-2c20-4bdf-8347-ce699d6f7959.png)

**Comment by PHSapper** [comment]
sorry it takes all 3 screens but it keeps telling me can not find conda environment pydarkstar

**Comment by AdamGagorik** [comment]
Did you follow the instructions to create the conda environment?  To double check you can type ‘conda env list’ in the terminal and paste a screenshot here.

**Comment by PHSapper** [comment]
![Screenshot (5)](https://user-images.githubusercontent.com/103973173/163911805-6cd08537-0cdb-4b6e-8f86-421c0606c9b8.png)

**Comment by PHSapper** [comment]
![Screenshot (6)](https://user-images.githubusercontent.com/103973173/163912740-b32aefd8-c48a-4508-8da0-9717d7110770.png)

**Comment by PHSapper** [comment]
![Screenshot (8)](https://user-images.githubusercontent.com/103973173/163914609-7c21ab95-0f3c-430f-93ea-42417e84e039.png)

**Comment by PHSapper** [comment]
I just followed this so what should I do next??
![Screenshot (10)](https://user-images.githubusercontent.com/103973173/163917780-4d8e9d28-fc9f-418e-968b-fb227f1dc515.png)
?

**Comment by PHSapper** [comment]
I have finally got it to work by figuring out cmd commands thru anaconda but I am still getting an error saying I am missing LOADER
![Screenshot (12)](https://user-images.githubusercontent.com/103973173/163919770-2b4a20dd-14af-4d83-921f-629c68c55dc6.png)

**Comment by PHSapper** [comment]
okay I got it all to load and work it says but I am confussed????? If it buys things how do we as players buy things??

**Comment by AdamGagorik** [comment]
If it’s working it will populate the AH with items for you as a player to buy while in game.  For example, just go to an AH and buy an item.

**Comment by TeoTwawki** [comment]
Worth noting it doesn't instantly fill AH on startup, unless you use the command (refill) specifically to do so. Otherwise it waits till its 1st cycle is up as defines by your config. People often run the broker ad think its not working when they don't instantly see items.

**Comment by AdamGagorik** [comment]
Calling this resolved.

**Comment by helixhamin** [comment]
> okay I got it all to load and work it says but I am confussed????? If it buys things how do we as players buy things??

Sorry but can you mention how you got it to load? I can't get it to work.
