### ISSUE TITLE
failed to parse <table>

### ISSUE THREAD

**Issue by LordKaT** [AdamGagorik/pydarkstar#4]
After building, all I get from the shell script is 60 INFO's of "failed to parse <table>", which ends up with a completely empty items.csv file.

The entire output of FFXIAHScrubber is just this:

...
[2015-03-04 12:42:28][24505][INFO ]: (0x242c810) FFXIAHScrubber: category 58/60 : http://www.ffxiah.com/browse/60/dice
[2015-03-04 12:42:28][24505][ERROR]: (0x242c810) FFXIAHScrubber: failed to parse <table>
[2015-03-04 12:42:28][24505][INFO ]: (0x242c810) FFXIAHScrubber: category 59/60 : http://www.ffxiah.com/browse/61/automatons
[2015-03-04 12:42:30][24505][ERROR]: (0x242c810) FFXIAHScrubber: failed to parse <table>
[2015-03-04 12:42:30][24505][INFO ]: (0x242c810) FFXIAHScrubber: category 60/60 : http://www.ffxiah.com/browse/62/grips
[2015-03-04 12:42:31][24505][ERROR]: (0x242c810) FFXIAHScrubber: failed to parse <table>

**Comment by AdamGagorik** [comment]
That sucks.

In the mean time, there is an already scrubbed items.csv file in the pydarkstar/data folder.  You can either copy it to the same directory as the broker script or pass its full path as a positional argument.

```bash
# for example (Linux)
cd /path/to/pydarkstar/bin
./broker.sh /path/to/pydarkstar/data/items.csv

# or copy it
cd /path/to/pydarkstar/bin
cp ../data/items.csv .
./broker.sh
```

That particular error means that the `<table>` tag was not found in the HTML.

As a check, I am rerunning the scrubber now, to see if ffxiah possibly changed their site layout.
It appears not to be the case from my end - parsing is working just fine for me.  When it finishes I can update the one in the data folder so you have the latest.

It is possible the internets were being temporarily weird, you may just want to retry running the scrub command.  I would use the --verbose option.

Could you tell me a little about the system you are running on?
* python2/python3, Linux/Windows, etc
* What about the version of python BeautifulSoup?
* exact command you ran (i.e. just scrub with no options)

You can check using interactive python.
```bash
Python 2.7.8 (default, Oct 20 2014, 15:05:19) 
[GCC 4.9.1] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import bs4
>>> print(bs4.__version__)
4.3.2
>>> 
```

**Comment by LordKaT** [comment]
Apologies, I should have looked into this further before posting. I had downloaded beautifulsoup4 from the Debian repo, not the pip installer, leaving me with a much older version of bs4.

Now that I've force-upgraded everything via pip the program seems to be running fine! I'll send a note to the Debian maintainer and let them know that they're pretty far out of date.

**Comment by AdamGagorik** [comment]
No worries, I am glad it is working.  Thanks for posting.
