### ISSUE TITLE
instructions need updated

### ISSUE THREAD

**Issue by TeoTwawki** [AdamGagorik/pydarkstar#8]
**`beautifulsoup4`**

instead of

**`beautiful-soup`**

when using pip (I've never used conda)

**Comment by TeoTwawki** [comment]
> `# to start the broker`
> `"C:\path\to\python3" .\broker.py`

results in 

> Traceback (most recent call last):
  File ".\broker.py", line 15, in <module>
    import pydarkstar.apps.broker.run
  File "D:\repository\pydarkstar\pydarkstar\apps\broker\run.py", line 9, in <module>
    from .options import Options
  File "D:\repository\pydarkstar\pydarkstar\apps\broker\options.py", line 5, in <module>
    from ...options.basic import BasicOptions
  File "D:\repository\pydarkstar\pydarkstar\options\basic.py", line 5, in <module>
    from .base import BaseOptions
  File "D:\repository\pydarkstar\pydarkstar\options\base.py", line 12, in <module>
    from six import add_metaclass
ModuleNotFoundError: No module named 'six'

**Comment by AdamGagorik** [comment]
This might be related to not using conda, which is fine.  Conda may install more modules by default than another Python distribution.  I would try `pip install six`.  If you see additional ModuleNotFoundErrors, continue installing them with pip.

**Comment by AdamGagorik** [comment]
With regards to the first part, it is mentioned on the requirements page.  Maybe this needs to be pointed out on the setup page.

http://adamgagorik.github.io/pydarkstar/generated/requirements.html

The setup page just assumes conda on windows to avoid setup problems.  The Linux instructions on the setup page are using pip.

http://adamgagorik.github.io/pydarkstar/generated/setup.html

**Comment by TeoTwawki** [comment]
Aye, needs pointed out. I was able to get the new ver working but a lot of people in Darkstars irc have given up pretty quickly. They also tend to not find the instructions till I link them to them (they usually fail to notice the large print "pydarkstar" in the readme takes them to your hithubpages url, then fail to notice the setup link under "features" and if I don't handhold them start to finish they just give up and say it doesn't work). I suggest putting setup links right in the read me once setup is updated for the "gotcha"s. While sometimes not the brightest bunch it saddens me to see ppl missing out on the best AH bot around. 😉

**Comment by AdamGagorik** [comment]
I will put the links in.

I really did try to make a good faith effort in the setup because I know not everyone who uses Darkstar is familiar with how things work with programs/command lines/scripts/etc.  Part of the problem is that people aren't reading the instructions that I wrote.  Possibly, as you say, because they can't find them.  I think there is also a subset of people who don't want to read anything at all (hence the handholding).

I think a lot of the complication arises from the fact that I did not set pydarkstar up so that it is installable.  For example, you can't just do `pip install pydarkstar`.  I wanted it so that you could just run the scripts from the pydarkstar directory.  I thought that would be easier.

**Comment by TeoTwawki** [comment]
Some of them give up at the part where they have to figure out they are using the wrong python ver too (and don't understand how to set up dual versions, even when they go get conda or I try to explain how to do this in a pip setup). Very much a prob of having not technical folks trying to use stuff that requires a minimum of knowhow. I appreciate your efforts, and hope I am helping.

**Comment by AdamGagorik** [comment]
I've made the changes you've suggested.  Hopefully people find it easier to adopt.
