### ISSUE TITLE
Dynamic prices/features assistance

### ISSUE THREAD

**Issue by sargcj** [AdamGagorik/pydarkstar#9]
Hello, I was wondering if I could get your assistance in working on some modifications to your program. 
Primarily I'm wanting to adjust the prices it buys and sells at(dynamically), but I haven't been able to quite figure out a few things. I suspect it would be simple for you to help me with. I'd also like to setup a name system where it trades names out. 

I'm currently stuck on trying to get the min, max, and average of the last 10 transactions with matching itemids.

**Comment by sargcj** [comment]
My more recent attempt at trying to understand python/sqlalchemy resulted in this, It still doesn't quite work and I'm not sure what all I'm doing wrong/not understanding.  I have been reviewing sqlalchemy, python tuts/documents/cheatsheets, and stack exchange to try and figure this out on my own, but so far no good.
Would you have any advice/tips/help @AdamGagorik ?
ps. I am an amateur in programming, and very new to python/sqlalchemy, so bear with my noobishness.

>recent = session.query(AuctionHouse.sale).order_by(AuctionHouse.sell_date()).limit(10)
                           
                            count = session.query(recent).count()
                            if count > 1:
                               min = session.query(func.avg(recent))
                               max = session.query(func.max(recent))
                               avg = session.query(func.min(recent))
>

**Comment by AdamGagorik** [comment]
Are you still working on this?

I think your approach should be to query the last 10 items of a given type.
Put their prices in a list and then use built-in python methods or numpy calls to calculate your statistics.
